Sprint2/step1
ssukhova-dev/react-burger pull request #5
Opened 2022-09-14 10:53 UTC by ssukhova-dev

2022-09-14 13:10 UTC, randomroot requested changes
Доброго времени суток!

Была проделана хорошая работа по реализации функционала взаимодействия с контекстами (причём как для заказа, так и для списка ингредиентов). Отдельно хотелось бы отметить наличие собственных хуков для модального окна и выполнения запросов, удачное разбиение на компоненты.

Однако, для успешного завершения этапа вам следует исправить пункты, отмеченные в рамках ревью, а также рассмотреть предложенные улучшения, которые позволят вам улучшить качество вашего кода, вкупе с производительностью приложения.

Кроме того, вам необходимо обратить внимание на следующие моменты:

1) Размер шрифта в карточке ингредиента не соответствует макету;
2) Часть отступов в карточке ингредиента не соответствуют макету;
3) В коде присутствуют лишние пустые строки и пробелы, проверьте его форматирование;

Успехов и хорошего дня 🐈

2022-09-14 13:10 UTC, randomroot commented on src/utils/burger-api.jsx
> +export function useFetch(requestFn)
🟢 **Отлично:**

Создание своего хука для решения повторяющихся проблем это крутая практика, так держать 👍

2022-09-14 13:10 UTC, randomroot commented on src/utils/burger-api.jsx
🟢 **Отлично:**

Вынос функционала работы с API в отдельный файл это правильная практика, уменьшающая дублирование кода и облегчающая процессы импорта нужных функций 👍

2022-09-14 13:10 UTC, randomroot commented on src/components/app/app.jsx
> +  const [selectedIngredients, setSelectedIngredients] = React.useState( []);
🟡 **Можно улучшить:**

В начальном состоянии перед массивом указан лишний пробел

2022-09-14 13:10 UTC, randomroot commented on src/components/app/app.jsx
> +                  Some error. Reload application, please.
🟡 **Можно улучшить:**

1) Такие текстовки можно вынести в файл с константами
2) Интерфейс в данном проекте на русском языке, поэтому и ошибки/сообщения желательно также выдавать на нём, вдруг среди пользователей попадется тот, кто его не понимает :)

2022-09-14 13:10 UTC, randomroot commented on src/components/app/app.jsx
> +          {hasError ? (
🟡 **Можно улучшить:**

Длинные выражения с тернарным оператором иногда бывает довольно непросто распознавать при чтении кода, иногда такие кейсы лучше разбить на отдельные if-ы и сделать несколько return-ов

2022-09-14 13:10 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +    setSelectedIngredients(ingredients);//временное решение
🟡 **Можно улучшить:**

В данном случае установка выбранных ингредиентов будет производится с каждым рендером, целесообразно в текущей ситуации вынести её в момент получения ингредиентов с сервера, обернув в `useEffect` или перенеся в функцию, где происходит запись в `IngredientsContext`

2022-09-14 13:10 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +        const bunIngredients = selectedIngredients.filter(item => item.type === IngredientTypes.bun )
🟡 **Можно улучшить:**

В текущей ситуации в выбранных ингредиентах может действительно оказаться несколько вариантов булок, но в перспективе с выбором ингредиента она будет в единственном числе, поэтому можно заменить функцию `filter` на функцию `find` (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

2022-09-14 13:10 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +    const bunIngredient = React.useMemo( getBunIngredient, [selectedIngredients]);
~~🔴 **Нужно исправить:**~~

~~В данном случае функция `getBunIngredient` будет пересоздаваться с каждым рендером, а `useMemo` запомнит её в рамках первого вызова, за счет замыкания, вследствие чего даже при изменении значения `selectedIngredients` внутри функции останется старое значение, а нужно использовать уже обновленное~~

2022-09-14 13:10 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +        let sum = bunIngredient ? (bunIngredient.price * 2) : 0;
🟡 **Можно улучшить:**

Данную переменную можно сделать константой и как сейчас передавать в начальное значение функции`reduce`, за счет чего можно будет сразу вернуть результат без промежуточной переменной `sum`

2022-09-14 13:10 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +
🟡 **Можно улучшить:**

В случае отсутствия propTypes данные строки кода можно безопасно удалить

2022-09-14 13:10 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +                            text={`${bunIngredient.name} (верх)`}
~~🔴 **Нужно исправить:**~~

~~В рамках `useMemo` вы можете вернуть значение равно `null`, которое приведет к ошибке обращения к значению переменной, следует добавить проверку на пустоту `bunIngredient`~~

2022-09-14 13:10 UTC, randomroot commented on src/components/burger-ingredient-card/burger-ingredient-card.jsx
> +              <div className={burgerIngCardStyle.burger_ingredient_card} onClick={()=>ingredientDetailsDlgRequest(ingredient)}>
🟡 **Можно улучшить:**

Инлайновые функции рекомендуется выносить в отдельные константы, для улучшения читабельности кода, хорошее описание возникающих проблем описано в документации от Airbnb, часто используемого в реальных проектах (см. https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md#react-hooks)

2022-09-14 13:10 UTC, randomroot commented on src/components/burger-ingredient-card/burger-ingredient-card.jsx
> +    ingredient: ingredientPropType,
🔴 **Нужно исправить:**

Значение ingredient в данном случае является обязательным, так как карточка ингредиента не может отображаться с пустым значением

2022-09-14 13:10 UTC, randomroot commented on src/components/burger-ingredient-card/burger-ingredient-card.jsx
> +    ingredientDetailsDlgRequest: PropTypes.func.isRequired
🟡 **Можно улучшить:**

Наименования пропсов желательно делать компактными и информативными, в данном случае не совсем понятно, за что данная функция отвечает. Например, если она отвечает только за закрытие окна, то можно её назвать `onToggleDialog`

2022-09-14 13:10 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +    const [total, totalDispatcher] = React.useReducer(getTotalReducer, 0, undefined);
🟢 **Отлично:**

Круто, что вам удалось применить хук `useReducer` для работы с данным значением 👍 

🟡 **Можно улучшить:**

Тем не менее несмотря на указания в задании здесь достаточно упростить данную функциональность, путём использования `useMemo` :)

2022-09-14 13:10 UTC, randomroot commented on src/utils/context.jsx
> +
🟡 **Можно улучшить:**

Целесообразно задавать начальные значения для контекста, чтобы не возникало случайных ошибок в компонентах использующих его в момент пока не были проброшены значения туда, например после запроса API. Чем меньше в проекте останется пустых значений, тем легче будет отладить его и обнаружить проблемы в сложной иерархии компонентов.

2022-09-14 13:10 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const mains = React.useMemo(() => ingredients.filter(item => item.type === IngredientTypes.main), [ingredients]);
🟡 **Можно улучшить:**

Обратите внимание, что для создания трех массивов в текущей реализации приходится проходиться по исходному массиву 3 раза, попробуйте улучшить эту часть кода, сократив до одного прохода, формируя все массивы сразу вместе :)

2022-09-14 13:10 UTC, randomroot commented on src/components/cart-total/cart-total.jsx
> +        for (let ingredient of selectedIngredients) {
🟡 **Можно улучшить:**

Данный функционал можно заменить на более современный метод в функциональном стиле `forEach` (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach), сделав переменную `ingredients` константой (чем меньше в коде потенциально изменяемых значений, тем выше его надежность)

2022-09-14 13:10 UTC, randomroot commented on src/components/cart-total/cart-total.jsx
> +        .catch(e => {
🔴 **Нужно исправить:**

Неиспользуемый код следует удалять, либо в данном случае наполнить функционалом логирования или вывода ошибки пользователю

2022-09-14 13:10 UTC, randomroot commented on src/components/cart-total/cart-total.jsx
> +    const [order, setOrder] = React.useState(0);
🟡 **Можно улучшить:**

В случае ID заказа, если значение еще не установлено, то лучше использовать `null` или `undefined` в качестве начального значения, чтобы случайно не вывести нуль на экран (вдруг заказ с таким номером станет акутальным)

2022-09-14 13:10 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                <Modal onClose={ingredientDetailsDlg.requestClose} title="Детали ингредиента">
🟡 **Можно улучшить:**

При закрытии диалога рекомендуется очищать значение выбранного ингредиента

2022-09-14 13:10 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +        return (bunIngredients.length == 0) ? null : bunIngredients[0];
🔴 **Нужно исправить:**

Для сравнения значения следует использовать строгое равенство для избежания проблем с преобразованием типов (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Equality_comparisons_and_sameness)

2022-09-14 13:10 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +            (item.type != IngredientTypes.bun) ? (sum + item.price) : sum), sum);
🔴 **Нужно исправить:**

Для сравнения значения следует использовать строгое неравенство для избежания проблем с преобразованием типов (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Equality_comparisons_and_sameness)

2022-09-14 13:10 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +                        (ingredient.type != IngredientTypes.bun) && (
🔴 **Нужно исправить:**

Для сравнения значения следует использовать строгое неравенство для избежания проблем с преобразованием типов (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Equality_comparisons_and_sameness)

2022-09-14 13:10 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
>  import PropTypes from 'prop-types';
🟡 **Можно улучшить:**

Неиспользуемые импорты можно безопасно удалить из кода

2022-09-14 13:10 UTC, randomroot commented on src/components/cart-total/cart-total.jsx
> +        .then(() => {
🔴 **Нужно исправить:**

В данном случае модальное окно будет открыто независимо от успешности выполнения запроса на создание заказа

2022-09-14 14:14 UTC, ssukhova-dev commented on src/components/burger-constructor/burger-constructor.jsx
> +                            text={`${bunIngredient.name} (верх)`}
{**bunIngredient** && (
                    <span className={burgerConstructorStyles.burger_bun} >
                        <ConstructorElement
                            type="top"
                            isLocked={true}
                            text={`${bunIngredient.name} (верх)`}
                            price={bunIngredient.price}
                            thumbnail={bunIngredient.image_mobile}       
                        />
                    </span>
                )}

а вот такой проверки не достаточно?
{**bunIngredient** && (

нужно еще добавить проверку? я не совсем поняла комментарий

2022-09-14 14:17 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +                            text={`${bunIngredient.name} (верх)`}
Приношу свои извинения, упустил этот момент, вашей проверки достаточно, комментарий снимается

2022-09-14 14:50 UTC, ssukhova-dev commented on src/components/cart-total/cart-total.jsx
> +        .then(() => {
мне кажется нет, потому что в функции getOrders есть checkResponse:

const checkResponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};

export const getOrders = (ingredients) => {

    return fetch(ORDERS_API_URL, {
                        method: 'POST',
                        headers: {
                        "Content-Type": "application/json"
                        },
                        body: JSON.stringify({ ingredients })})
            .then(checkResponse)
};

2022-09-14 14:53 UTC, randomroot commented on src/components/cart-total/cart-total.jsx
> +        .then(() => {
А если рассмотреть кейс, когда в ответе будет `data.success === false`?

2022-09-15 11:13 UTC, randomroot approved these changes
🟢 **Работа принята**

Добрый день! Вы отлично справились с поставленной задачей, работа содержит полезными дополнения для улучшения UI и качества кода. Замечаний к вашей работе более не имеется, особо хотел бы отметить вашу внимательность к замечаниям и оперативное исправление, согласно комментариям.

Успехов в дальнейшем обучении! 🐈

2022-09-15 11:13 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +    const bunIngredient = React.useMemo( getBunIngredient, [selectedIngredients, getBunIngredient]);
🟡 **Можно улучшить:**

Обсудили вопрос с вашим наставником, дополнительный аргумент в зависимостях `useMemo` не потребуется, можете оставить предыдущий вариант.

2022-09-15 11:34 UTC, merged